replicaCount: 1

image:
  repository: nginx
  tag: latest

configmap:
  name: nginx-html-config
  content: |
    <!DOCTYPE html>
    <html>
      <body>
        <h1>Welcome to Kubernetes!</h1>
        <p>This is a default Helm environment.</p>
      </body>
    </html>

service:
  type: ClusterIP 
  port: 80         # Port exposed externally
  nodePort: {}

ingress: {}