apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-helm.serviceName" . }}  # Using helper function for service name
  labels:
    {{- include "nginx-helm.labels" . }}  
spec:
  type: {{ .Values.service.type }}   
  ports:
    - port: {{ .Values.service.port }}  
      targetPort: 80                    
      protocol: TCP
      name: http
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort | quote }}   
      {{- end }}
  selector:
    app: {{ .Release.Name }}  