apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2048-web-game
  labels:
    app: 2048-web-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 2048-web-game
  template:
    metadata:
      labels:
        app: 2048-web-game
    spec:
      containers:
      - name: web-game
        image: evilroot/docker-2048
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: 2048-web-game-service
spec:
  type: LoadBalancer
  selector:
    app: 2048-web-game
  ports:
  - port: 80
    targetPort: 80