apiVersion: v2
name: car-rental-umbrella
description: Helm umbrella chart for Car Rental App
type: application
version: 0.1.0
dependencies:
  - name: car-rental-ui
    version: 0.1.0
    repository: file://charts/car-rental-ui
  - name: car-rental-api
    version: 0.1.0
    repository: file://charts/car-rental-api
  - name: mysqldb-service
    version: 8.0.0
    repository: https://charts.bitnami.com/bitnami   # or your own MySQL chart