version: '3.8'

services:
  mysqldbserver:
    image: mysql:latest
    container_name: mysql-db-server
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: car_rental_db
    ports:
      - "3306:3306"
    restart: always
    networks:
      - car-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot123"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: car-rental-api:latest
    container_name: car-rental-api
    depends_on:
      mysqldbserver:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      DB_HOST: mysqldbserver
      DB_PORT: 3306
      DB_NAME: car_rental_db
      DB_USER: root
      DB_PASSWORD: root123
    volumes:
      - .:/app       # Mount source code
      # - ~/.gradle:/home/gradle/.gradle  # Optional: reuse Gradle cache
    networks:
      - car-network

networks:
  car-network:
    driver: bridge