version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: carrental-c
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: car_rental_db
    ports:
      - "3306:3306"
    restart: always
    networks:
      - my-network
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    image: car-rental-api:0.1
    container_name: car-rental-api
    depends_on:
      - mysql
    networks:
      - my-network
    ports:
      - "8080:8080"  # Adjust if your app runs on a different port
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: car_rental_db
      DB_USER: root
      DB_PASSWORD: root123

networks:
  my-network:
    driver: bridge

volumes:
  mysql_data:
