apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-ui-react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-ui-react
  template:
    metadata:
      labels:
        app: book-ui-react
    spec:
      containers:
      - name: book-ui-react-container
        image: akumarraj/apps:book-reactui-0.1

---
apiVersion: v1
kind: Service
metadata:
  name: book-ui-react-app-service
  labels:
    service: book-ui-react-app-http-service
spec:
  selector:
    app: book-ui-react
  ports:
    - name: http 
      protocol: TCP
      port: 4173 # exposed port
      targetPort: 4173 # Container port
  type: NodePort