apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-nodeapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-nodeapi
  template:
    metadata:
      labels:
        app: book-nodeapi
    spec:
      containers:
      - name: book-nodeapi-container
        image: akumarraj/apps:book-api-node-0.1

---
apiVersion: v1
kind: Service
metadata:
  name: book-nodeapi-app-service
  labels:
    service: book-nodeapi-app-http-service
spec:
  selector:
    app: book-nodeapi
  ports:
    - name: http 
      protocol: TCP
      port: 3000 # exposed port
      targetPort: 3000 # Container port
  type: NodePort