apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job
spec:
  template:
    spec:
      containers:
      - name: hello
        image: busybox
        command: ["sh", "-c", "echo 👋 Hello from Kubernetes Job! && sleep 10"]
      restartPolicy: Never
  backoffLimit: 4