apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-backup-job
spec:
  template:
    spec:
      containers:
      - name: mysql-backup
        image: mysql:5.7
        env:
        - name: MYSQL_HOST
          value: "mysql-service"  # Replace with your MySQL service name
        - name: MYSQL_USER
          value: "root"  # Replace with your MySQL username
        - name: MYSQL_PASSWORD
          value: "password"  # Replace with your MySQL password
        - name: MYSQL_DATABASE
          value: "my_database"  # Replace with your database name
        command: ["/bin/sh", "-c"]
        args:
          - "mysqldump -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE > /backup/backup.sql && echo 'Backup completed!'"
        volumeMounts:
        - name: backup-volume
          mountPath: /backup
      restartPolicy: Never
      volumes:
      - name: backup-volume
        hostPath:
          path: /mnt/data/backups  # Local path where the backup will be stored
          type: Directory
  backoffLimit: 3
