## ConfigMap-1
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html-config
data:
  custom-k8s-welcome.html: |
    <!DOCTYPE html>
    <html>
      <body>
        <h1>Welcome to Kubernetes! 🚀</h1>
        <p>This page is served from a ConfigMap. 📦</p>
      </body>
    </html>

---
## Deployment-1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web-server101
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx101
  template:
    metadata:
      labels:
        app: nginx101
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html/index.html
          subPath: custom-k8s-welcome.html
      volumes:
      - name: html-volume
        configMap:
          name: nginx-html-config

---
### ConfigMap-2
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  APP_MODE: "production"
  APP_VERSION: "1.0.3"
  WELCOME_MSG: "Hello from K8s ConfigMap 👋"

---
## Deployment-2
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-busybox-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-busybox-app
  template:
    metadata:
      labels:
        app: demo-busybox-app
    spec:
      containers:
      - name: demo-container
        image: busybox
        command: ["sh", "-c", "env; sleep 3600"] # Just to demo env vars
        envFrom:
        - configMapRef:
            name: app-config




