## PVC 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard

---

## Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookapi-spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookapi-spring
  template:
    metadata:
      labels:
        app: bookapi-spring
    spec:
      containers:
      - name: bookapispring
        image: akumarraj/apps:bookapi-spring-0.1
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 20
        volumeMounts:
        - name: log-volume
          mountPath: /app/logs
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "250m"
      volumes:
        - name: log-volume
          persistentVolumeClaim:
            claimName: app-pvc

---

## Service
apiVersion: v1
kind: Service
metadata:
  name: bookapi-spring-service
spec:
  selector:
    app: bookapi-spring
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080  # Optional
