apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-web-server
  template:
    metadata:
      labels:
        app: nginx-web-server
    spec:
      containers:
      - name: nginx-server
        image: nginx:latest
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html/index.html
          subPath: k8s-welcome.html
        - name: podname
          mountPath: /usr/share/nginx/html/podinfo
          subPath: podname
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "50m"
      volumes:
        - name: html-volume
          configMap:
            name: nginx-html 
        - name: podname
          downwardAPI:
            items:
            - path: "podname"
              fieldRef:
                fieldPath: metadata.name

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip-service
  labels:
    service: nginx-cip-http-service
spec:
  selector:
    app: nginx-web-server
  ports:
    - name: http 
      protocol: TCP
      port: 80 # exposed port
      targetPort: 80 # Container port
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-service 
  labels:
    service: nginx-np-http-service
spec:
  selector:
    app: nginx-web-server
  ports:
    - name: http 
      protocol: TCP
      port: 80 # exposed port
      targetPort: 80 # Container port
      nodePort: 31000
  type: NodePort
---

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-lg-service
  labels:
    service: nginx-lg-http-service
spec:
  selector:
    app: nginx-web-server
  ports:
    - name: http 
      protocol: TCP
      port: 80 # exposed port
      targetPort: 80 # Container port
  type: LoadBalancer

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: nginx.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-lg-service
            port:
              number: 80