apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web-server2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-web-server2
  template:
    metadata:
      labels:
        app: nginx-web-server2
    spec:
      containers:
      - name: nginx-server
        image: nginx:latest