apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <title>Welcome to K8s</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          background: #f9f9f9;
          text-align: center;
          padding-top: 50px;
        }
        img {
          width: 200px;
          margin-top: 20px;
        }
        .container {
          background: white;
          padding: 30px;
          display: inline-block;
          box-shadow: 0 0 10px rgba(0,0,0,0.1);
          border-radius: 10px;
        }
      </style>
    </head>
    <body>
      <div class="container">
        <h1>Hello World 🌍</h1>
        <h2>Welcome to K8s Learning 🎓</h2>
        <p>Serving static content using <strong>Nginx</strong> 🚀</p>
        <img src="https://miro.medium.com/v2/resize:fit:1400/0*ifO8L2ahNhhf9P4k.png" alt="Nginx Logo">
        <p id="pod-info">Pod name: <span id="pod-name">loading...</span></p>
      </div>

      <script>
        fetch('/podinfo')
          .then(response => response.text())
          .then(name => {
            document.getElementById('pod-name').textContent = name.trim();
          })
          .catch(err => {
            document.getElementById('pod-name').textContent = 'unavailable';
          });
      </script>
    </body>
    </html>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
        - name: podname
          mountPath: /usr/share/nginx/html/podinfo
          subPath: podname
      volumes:
      - name: html-volume
        configMap:
          name: nginx-html
      - name: podname
        downwardAPI:
          items:
          - path: "podname"
            fieldRef:
              fieldPath: metadata.name


---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort