replicaCount: 1

image:
  repository: akumarraj/apps
  tag: car-rental-ui-0.1
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 4173
  targetPort: 4173
  nodePort: 30081

env:
  VITE_API_URL: http://car-rental-api-service:80

resources: {}
  # limits:
  #   cpu: 500m
  #   memory: 512Mi
  # requests:
  #   cpu: 250m
  #   memory: 256Mi

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70

securityContext:
  runAsUser: 1000
  runAsGroup: 3000
  fsGroup: 2000
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true