pipeline {
    agent any
    environment {
        VERSION = '1.0.0'
    }
    stages {
        stage('Setup Virtual Environment') {
            steps {
                dir('projects/python-calci-app') {
                    echo 'Setting up Python virtual environment...'
                    sh 'python3 -m venv venv'
                    sh 'source venv/bin/activate'
                }
            }
        }
        stage('Install Dependencies') {
            steps {
                dir('projects/python-calci-app') {
                    echo 'Installing dependencies...'
                    sh 'pip install -r requirements.txt'
                }
            } 
        }
        stage('Lint') {
            steps {
                dir('projects/python-calci-app') {
                    echo 'Running linting...'
                    sh 'pylint *.py'
                }
            }
        }
        stage('Test') {
            steps {
                dir('projects/python-calci-app') {
                    echo 'Running unit tests...'
                    sh 'pytest'
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline succeeded!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}