pipeline {
    agent any
    environment {
        VERSION = '1.0.0'
    }
    stages {
        stage('Setup Virtual Environment') {
            steps {
                dir('projects/python-calci-app') {
                    echo 'Setting up Python virtual environment...'
                    sh '''#!/bin/bash
                    python3 --version || echo "Python3 not found"
                    python3 -m pip --version || echo "pip not installed"
                    python3 -m venv venv
                    source venv/bin/activate
                    pip install -r requirements.txt
                    '''
                }
            }
        }
        stage('Lint') {
            steps {
                dir('projects/python-calci-app') {
                    echo 'Running linting...'
                    sh '''#!/bin/bash
                    source venv/bin/activate
                    pylint *.py
                    '''
                }
            }
        }
        stage('Test') {
            steps {
                dir('projects/python-calci-app') {
                    echo 'Running unit tests...'
                    sh '''#!/bin/bash
                    source venv/bin/activate
                    pytest
                    '''
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline succeeded!'
        }
        failure {
            echo 'Pipeline failed!'
        }

        always{
            cleanWs() // Delete the workspace
        }
    }
}