## Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-stress-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-stress
  template:
    metadata:
      labels:
        app: memory-stress
    spec:
      containers:
      - name: memory-stress
        image: akumarraj/apps:memorystress-0.1
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "50Mi"
          limits:
            memory: "100Mi"
---
## Service
apiVersion: v1
kind: Service
metadata:
  name: memory-stress-service
spec:
  selector:
    app: memory-stress
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
  type: NodePort

---
## VPA 
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: memory-stress-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: memory-stress-app
  updatePolicy:
    updateMode: "Auto"
