# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-stress-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-stress
  template:
    metadata:
      labels:
        app: cpu-stress
    spec:
      containers:
      - name: cpu-stress
        image: akumarraj/apps:cpustressapp-0.1
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 50m
          limits:
            cpu: 75m
---
## Service
apiVersion: v1
kind: Service
metadata:
  name: cpu-stress-service
spec:
  selector:
    app: cpu-stress
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000
  type: NodePort

---
### HPA 
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cpu-stress-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cpu-stress-app
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
