apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "car-rental-api.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: car-rental-api
  template:
    metadata:
      labels:
        app: car-rental-api
    spec:
      containers:
        - name: car-rental-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: DB_URL
              value: {{ .Values.env.dbUrl | quote }}
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRef.name }}
                  key: {{ .Values.secretRef.dbUserKey }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRef.name }}
                  key: {{ .Values.secretRef.dbPasswordKey }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: logs-car-rental-api
              mountPath: /app/logs
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 3000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
                - KILL
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
      volumes:
        - name: logs-car-rental-api
          persistentVolumeClaim:
            claimName: {{ include "car-rental-api.fullname" . }}-pvc