apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "car-rental-api.fullname" . }}-mysql-policy
spec:
  podSelector:
    matchLabels:
      app: mysql
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: car-rental-api
      ports:
        - protocol: TCP
          port: 3306