apiVersion: v1
kind: Service
metadata:
  name: {{ include "car-rental-api.fullname" . }}-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: car-rental-api
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}