pipeline {
    agent {
        docker {
            image 'maven:3.8.6-jdk-11'
            args '-v /tmp:/tmp'
        }
    }

    stages {
        stage('Checkout Code') {
            steps {
                echo 'Checking out code from repository...'
                git branch: 'main', url: 'https://github.com/anil-k-rajamoni18/JavaBackendDevOps.git'
            }
        }

        stage('Navigate to projects directory') {
            steps {
                echo 'Navigating to projects directory...'
                dir('projects/sample-maven') {
                    echo 'Current directory: ' + pwd()
                }
            }
        }

        stage('Build') {
            steps {
                echo 'Building the Maven project...'
                dir('projects/sample-maven') {
                    sh 'mvn clean compile'
                }
            }
        }

        stage('Test') {
            steps {
                echo 'Running unit tests...'
                dir('projects/sample-maven') {
                    sh 'mvn test'
                }
            }
            post {
                always {
                    junit 'projects/sample-maven-project/target/surefire-reports/*.xml'
                }
            }
        }

        stage('Package') {
            steps {
                echo 'Packaging the application...'
                dir('projects/sample-maven') {
                    sh 'mvn package'
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline succeeded!'
        }
        failure {
            echo 'Pipeline failed!'
        }
        always {
            echo 'Cleaning up workspace...'
            cleanWs() // Delete the workspace
        }
    }
}