replicaCount: 1

image:
  repository: akumarraj/apps
  tag: car-rental-api-0.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8081

env:
  dbUrl: jdbc:mysql://mysqldb-service:3306/car_rental_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

secretRef:
  name: mysqldb-service-secret
  dbUserKey: mysql-user
  dbPasswordKey: mysql-password

persistence:
  enabled: true
  storageClass: standard
  accessModes:
    - ReadWriteOnce
  size: 1Gi

resources: {}
  # limits:
  #   cpu: 500m
  #   memory: 512Mi
  # requests:
  #   cpu: 250m
  #   memory: 256Mi


hpa:
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80