apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-api
  template:
    metadata:
      labels:
        app: book-api
    spec:
      containers:
      - name: api
        image: 767828743650.dkr.ecr.ap-south-2.amazonaws.com/dev/apps:node-book-api-1.0
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: book-api
spec:
  selector:
    app: book-api
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
