version: '3.8'

services:
  backend:
    image: node-backend-bookapi:0.1
    container_name: bookapi-backend
    ports:
      - "3000:3000"  # Adjust if your backend runs on a different port
    restart: always
    networks:
      - bookapi-network

  frontend:
    image: react-ui-bookapi:0.1
    container_name: bookapi-frontend
    ports:
      - "4173:4173"  # React app typically runs on 3000
    restart: always
    depends_on:
      - backend
    networks:
      - bookapi-network

  api:
    image: nginx:latest
    container_name: nginx-api
    ports:
      - "8000:80"
    restart: always
    depends_on:
      - backend
    volumes:
      - ./site-content:/usr/share/nginx/html
    networks:
      - bookapi-network 

networks:
  bookapi-network:
    driver: bridge