apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "car-rental-ui.fullname" . }}
  labels:
    app: car-rental-ui-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: car-rental-ui-app
  template:
    metadata:
      labels:
        app: car-rental-ui-app
    spec:
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
      containers:
        - name: car-rental-ui-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: VITE_API_URL
              value: {{ .Values.env.VITE_API_URL | quote }}
          volumeMounts:
          - name: vite-temp
            mountPath: /app/node_modules/.vite-temp
          securityContext:
            allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
            readOnlyRootFilesystem: {{ .Values.securityContext.readOnlyRootFilesystem }}
            runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
      volumes:
      - name: vite-temp
        emptyDir: {}
