replicaCount: 1

image:
  repository: mysql
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3306

mysql:
  database: car_rental_db
  user: caruser
  password: carpass
  rootPassword: password

persistence:
  enabled: true
  storageClass: standard
  accessModes:
    - ReadWriteOnce
  size: 1Gi

resources: {}
  # limits:
  #   cpu: 500m
  #   memory: 512Mi
  # requests:
  #   cpu: 250m
  #   memory: 256Mi