apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.fullname" . }}-secret
type: Opaque
data:
  mysql-root-password: {{ .Values.mysql.rootPassword | b64enc }}
  mysql-user: {{ .Values.mysql.user | b64enc }}
  mysql-password: {{ .Values.mysql.password | b64enc }}